# Generated by Django 2.2 on 2019-04-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image_url',
            field=models.ImageField(default='nothingImg', upload_to='images/'),
        ),
    ]
