# Generated by Django 2.2 on 2019-04-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entry_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='genre',
            field=models.CharField(default='', max_length=10),
        ),
    ]
